name: email-sending-with-files
on: [push]
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/gibibm/progetto-esp32
      - run: ls -l
      - uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          path: ./progetto-esp32
      - run: ls -l
      - uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 3AI Voicu e Gibellino - Nuovo commit sulla repo
          # Literal body:
          body: È stato creato un commit sulla repository di Voicu e Gibellino di 3AI. https://github.com/gibibm/progetto-esp32
          # Read file contents as body:
          # body: file://githubactions-test/index.js
          to: everlastmailplay@gmail.com
          from: Angelo Voicu # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/plain
          # Optional attachments:
          attachments: ./release.zip
