name: email-sending-with-files
on: [push]
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/gibibm/progetto-esp32
      - uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 
          # Literal body:
          body: È stato creato un commit sulla repository ${{github.repository}} di Voicu e Gibellino di 3AI.
          # Read file contents as body:
          # body: file://githubactions-test/index.js
          to: everlastmailplay@gmail.com
          from: Angelo Voicu # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/plain
          # Optional attachments:
          attachments: ./progetto-esp32/Web\ App/index.html
